// SPDX-License-Identifier: MIT

#ifndef _HTTP_CORE
#define _HTTP_CORE

#define HTTP10 10 // HTTP 1.0
#define HTTP11 11 // HTTP 1.1
#define HTTP20 20 // HTTP 2.0
#define HTTP30 30 // HTTP 3.0

#define HTTP10_STR "HTTP/1.0"
#define HTTP11_STR "HTTP/1.1"
#define HTTP20_STR "HTTP/2.0"
#define HTTP30_STR "HTTP/3.0"

// Status codes
#define INFO_CONTINUE 100
#define INFO_SWITCH_PROTOCOLS 101
#define INFO_PROCESSING 102
#define INFO_EARLY_HINTS 103

#define SUCCESS_OK 200
#define SUCCESS_CREATED 201
#define SUCCESS_ACCEPTED 202
#define SUCCESS_NON_AUTHORITATIVE_INFORMATION 203
#define SUCCESS_NO_CONTENT 204
#define SUCCESS_RESET_CONTENT 205
#define SUCCESS_PARTIAL_CONTENT 206
#define SUCCESS_MULTI_STATUS 207
#define SUCCESS_ALREADY_REPORTED 208
#define SUCCESS_THIS_IS_FINE 218
#define SUCCESS_IM_USED 226

#define REDIRECT_MULTIPLE_CHOICES 300
#define REDIRECT_MOVED_PERMANENTLY 301
#define REDIRECT_FOUND 302
#define REDIRECT_SEE_OTHER 303
#define REDIRECT_NOT_MODIFIED 304
#define REDIRECT_USE_PROXY 305
#define REDIRECT_SWITCH_PROXY 306
#define REDIRECT_TEMPORARY_REDIRECT 307
#define REDIRECT_PERMANENT_REDIRECT 308

#define ERROR_BAD_REQUEST 400
#define ERROR_UNAUTHORIZED 401
#define ERROR_PAYMENT_REQUIRED 402
#define ERROR_FORBIDDEN 403
#define ERROR_NOT_FOUND 404
#define ERROR_METHOD_NOT_ALLOWED 405
#define ERROR_NOT_ACCEPTABLE 406
#define ERROR_PROXY_AUTHENTICATION_REQUIRED 407
#define ERROR_REQUEST_TIMEOUT 408
#define ERROR_CONFLICT 409
#define ERROR_GONE 410
#define ERROR_LENGTH_REQUIRED 411
#define ERROR_PRECONDITION_FAILED 412
#define ERROR_PAYLOAD_TOO_LARGE 413
#define ERROR_URI_TOO_LONG 414
#define ERROR_UNSUPPORTED_MEDIA_TYPE 415
#define ERROR_RANGE_NOT_SATISFIABLE 416
#define ERROR_EXPECTATION_FAILED 417
#define ERROR_IM_A_TEAPOT 418
#define ERROR_PAGE_EXPIRED 419
#define ERROR_METHOD_FAILURE_OR_ENHANCE_YOUR_CALM 420
#define ERROR_MISDIRECTED_REQUEST 421
#define ERROR_UNPROCESSABLE_ENTITY 422
#define ERROR_LOCKED 423
#define ERROR_FAILED_DEPENDENCY 424
#define ERROR_TOO_EARLY 425
#define ERROR_UPGRADE_REQUIRED 426
#define ERROR_PRECONDITION_REQUIRED 428
#define ERROR_TOO_MANY_REQUESTS 429
#define ERROR_HTTP_STATUS_CODE 430
#define ERROR_REQUEST_HEADER_FIELDS_TOO_LARGE 431
#define ERROR_LOGIN_TIME_OUT 440
#define ERROR_NO_RESPONSE 444
#define ERROR_RETRY_WITH 449
#define ERROR_BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS 450
#define ERROR_UNAVAILABLE_FOR_LEGAL_REASONS 451
#define ERROR_CLIENT_CLOSED_CONNECTION_PREMATURELY 460
#define ERROR_TOO_MANY_FORWARDED_IP_ADDRESSES 463
#define ERROR_INCOMPATIBLE_PROTOCOL 464
#define ERROR_REQUEST_HEADER_TOO_LARGE 494
#define ERROR_SSL_CERTIFICATE_ERROR 495
#define ERROR_SSL_CERTIFICATE_REQUIRED 496
#define ERROR_HTTP_REQUEST_SENT_TO_HTTPS_PORT 497
#define ERROR_INVALID_TOKEN 498
#define ERROR_TOKEN_REQUIRED_OR_CLIENT_CLOSED_REQUEST 499

#define CRIT_INTERNAL_SERVER_ERROR 500
#define CRIT_NOT_IMPLEMENTED 501
#define CRIT_BAD_GATEWAY 502
#define CRIT_SERVICE_UNAVAILABLE 503
#define CRIT_GATEWAY_TIMEOUT 504
#define CRIT_HTTP_VERSION_NOT_SUPPORTED 505
#define CRIT_VARIANT_ALSO_NEGOTIATES 506
#define CRIT_INSUFFICIENT_STORAGE 507
#define CRIT_LOOP_DETECTED 508
#define CRIT_BANDWIDTH_LIMIT_EXCEEDED 509
#define CRIT_NOT_EXTENDED 510
#define CRIT_NETWORK_AUTHENTICATION_REQUIRED 511
#define CRIT_WEB_SERVER_IS_RETURNING_AN_UNKNOWN_ERROR 520
#define CRIT_WEB_SERVER_IS_DOWN 521
#define CRIT_CONNECTION_TIMED_OUT 522
#define CRIT_ORIGIN_IS_UNREACHABLE 523
#define CRIT_A_TIMEOUT_OCCURRED 524
#define CRIT_SSL_HANDSHAKE_FAILED 525
#define CRIT_INVALID_SSL_CERTIFICATE 526
#define CRIT_RAILGUN_LISTENER_TO_ORIGIN 527
#define CRIT_THE_SERVICE_IS_OVERLOADED 529
#define CRIT_SITE_FROZEN 530
#define CRIT_UNAUTHORIZED 561
#define CRIT_NETWORK_READ_TIMEOUT_ERROR 598
#define CRIT_NETWORK_CONNECT_TIMEOUT_ERROR 599

// Status codes strings
#define INFO_CONTINUE_STRING "Continue"
#define INFO_SWITCH_PROTOCOLS_STRING "Switching Protocols"
#define INFO_PROCESSING_STRING "Processing"
#define INFO_EARLY_HINTS_STRING "Early Hints"

#define SUCCESS_OK_STRING "OK"
#define SUCCESS_CREATED_STRING "Created"
#define SUCCESS_ACCEPTED_STRING "Accepted"
#define SUCCESS_NON_AUTHORITATIVE_INFORMATION_STRING "Non-Authoritative Information"
#define SUCCESS_NO_CONTENT_STRING "No Content"
#define SUCCESS_RESET_CONTENT_STRING "Reset Content"
#define SUCCESS_PARTIAL_CONTENT_STRING "Partial Content"
#define SUCCESS_MULTI_STATUS_STRING "Multi-Status"
#define SUCCESS_ALREADY_REPORTED_STRING "Already Reported"
#define SUCCESS_THIS_IS_FINE_STRING "This Is Fine"
#define SUCCESS_IM_USED_STRING "IM Used"

#define REDIRECT_MULTIPLE_CHOICES_STRING "Multiple Choices"
#define REDIRECT_MOVED_PERMANENTLY_STRING "Moved Permanently"
#define REDIRECT_FOUND_STRING "Found"
#define REDIRECT_SEE_OTHER_STRING "See Other"
#define REDIRECT_NOT_MODIFIED_STRING "Not Modified"
#define REDIRECT_USE_PROXY_STRING "Use Proxy"
#define REDIRECT_SWITCH_PROXY_STRING "Switch Proxy"
#define REDIRECT_TEMPORARY_REDIRECT_STRING "Temporary Redirect"
#define REDIRECT_PERMANENT_REDIRECT_STRING "Permanent Redirect"

#define ERROR_BAD_REQUEST_STRING "Bad Request"
#define ERROR_UNAUTHORIZED_STRING "Unauthorized"
#define ERROR_PAYMENT_REQUIRED_STRING "Payment Required"
#define ERROR_FORBIDDEN_STRING "Forbidden"
#define ERROR_NOT_FOUND_STRING "Not Found"
#define ERROR_METHOD_NOT_ALLOWED_STRING "Method Not Allowed"
#define ERROR_NOT_ACCEPTABLE_STRING "Not Acceptable"
#define ERROR_PROXY_AUTHENTICATION_REQUIRED_STRING "Proxy Authentication Required"
#define ERROR_REQUEST_TIMEOUT_STRING "Request Timeout"
#define ERROR_CONFLICT_STRING "Conflict"
#define ERROR_GONE_STRING "Gone"
#define ERROR_LENGTH_REQUIRED_STRING "Length Required"
#define ERROR_PRECONDITION_FAILED_STRING "Precondition Failed"
#define ERROR_PAYLOAD_TOO_LARGE_STRING "Payload Too Large"
#define ERROR_URI_TOO_LONG_STRING "URI Too Long"
#define ERROR_UNSUPPORTED_MEDIA_TYPE_STRING "Unsupported Media Type"
#define ERROR_RANGE_NOT_SATISFIABLE_STRING "Range Not Satisfiable"
#define ERROR_EXPECTATION_FAILED_STRING "Expectation Failed"
#define ERROR_IM_A_TEAPOT_STRING "I'm a Teapot"
#define ERROR_PAGE_EXPIRED_STRING "Page Expired"
#define ERROR_METHOD_FAILURE_OR_ENHANCE_YOUR_CALM_STRING "Method Failure or Enhance Your Calm"
#define ERROR_MISDIRECTED_REQUEST_STRING "Misdirected Request"
#define ERROR_UNPROCESSABLE_ENTITY_STRING "Unprocessable Entity"
#define ERROR_LOCKED_STRING "Locked"
#define ERROR_FAILED_DEPENDENCY_STRING "Failed Dependency"
#define ERROR_TOO_EARLY_STRING "Too Early"
#define ERROR_UPGRADE_REQUIRED_STRING "Upgrade Required"
#define ERROR_PRECONDITION_REQUIRED_STRING "Precondition Required"
#define ERROR_TOO_MANY_REQUESTS_STRING "Too Many Requests"
#define ERROR_HTTP_STATUS_CODE_STRING "HTTP Status Code"
#define ERROR_REQUEST_HEADER_FIELDS_TOO_LARGE_STRING "Request Header Fields Too Large"
#define ERROR_LOGIN_TIME_OUT_STRING "Login Time-Out"
#define ERROR_NO_RESPONSE_STRING "No Response"
#define ERROR_RETRY_WITH_STRING "Retry With"
#define ERROR_BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS_STRING "Blocked by Windows Parental Controls"
#define ERROR_UNAVAILABLE_FOR_LEGAL_REASONS_STRING "Unavailable For Legal Reasons"
#define ERROR_CLIENT_CLOSED_CONNECTION_PREMATURELY_STRING "Client Closed Connection Prematurely"
#define ERROR_TOO_MANY_FORWARDED_IP_ADDRESSES_STRING "Too Many Forwarded IP Addresses"
#define ERROR_INCOMPATIBLE_PROTOCOL_STRING "Incompatible Protocol"
#define ERROR_REQUEST_HEADER_TOO_LARGE_STRING "Request Header Too Large"
#define ERROR_SSL_CERTIFICATE_ERROR_STRING "SSL Certificate Error"
#define ERROR_SSL_CERTIFICATE_REQUIRED_STRING "SSL Certificate Required"
#define ERROR_HTTP_REQUEST_SENT_TO_HTTPS_PORT_STRING "HTTP Request Sent to HTTPS Port"
#define ERROR_INVALID_TOKEN_STRING "Invalid Token"
#define ERROR_TOKEN_REQUIRED_OR_CLIENT_CLOSED_REQUEST_STRING "Token Required or Client Closed Request"

#define CRIT_INTERNAL_SERVER_ERROR_STRING "Internal Server Error"
#define CRIT_NOT_IMPLEMENTED_STRING "Not Implemented"
#define CRIT_BAD_GATEWAY_STRING "Bad Gateway"
#define CRIT_SERVICE_UNAVAILABLE_STRING "Service Unavailable"
#define CRIT_GATEWAY_TIMEOUT_STRING "Gateway Timeout"
#define CRIT_HTTP_VERSION_NOT_SUPPORTED_STRING "HTTP Version Not Supported"
#define CRIT_VARIANT_ALSO_NEGOTIATES_STRING "Variant Also Negotiates"
#define CRIT_INSUFFICIENT_STORAGE_STRING "Insufficient Storage"
#define CRIT_LOOP_DETECTED_STRING "Loop Detected"
#define CRIT_BANDWIDTH_LIMIT_EXCEEDED_STRING "Bandwidth Limit Exceeded"
#define CRIT_NOT_EXTENDED_STRING "Not Extended"
#define CRIT_NETWORK_AUTHENTICATION_REQUIRED_STRING "Network Authentication Required"
#define CRIT_WEB_SERVER_IS_RETURNING_AN_UNKNOWN_ERROR_STRING "Web Server Is Returning an Unknown Error"
#define CRIT_WEB_SERVER_IS_DOWN_STRING "Web Server Is Down"
#define CRIT_CONNECTION_TIMED_OUT_STRING "Connection Timed Out"
#define CRIT_ORIGIN_IS_UNREACHABLE_STRING "Origin Is Unreachable"
#define CRIT_A_TIMEOUT_OCCURRED_STRING "A Timeout Occurred"
#define CRIT_SSL_HANDSHAKE_FAILED_STRING "SSL Handshake Failed"
#define CRIT_INVALID_SSL_CERTIFICATE_STRING "Invalid SSL Certificate"
#define CRIT_RAILGUN_LISTENER_TO_ORIGIN_STRING "Railgun Listener to Origin"
#define CRIT_THE_SERVICE_IS_OVERLOADED_STRING "The Service Is Overloaded"
#define CRIT_SITE_FROZEN_STRING "Site Frozen"
#define CRIT_UNAUTHORIZED_STRING "Unauthorized"
#define CRIT_NETWORK_READ_TIMEOUT_ERROR_STRING "Network Read Timeout Error"
#define CRIT_NETWORK_CONNECT_TIMEOUT_ERROR_STRING "Network Connect Timeout Error"

#define HTTP_PATH_MAX 4096
#define HTTP_HEADERS_MAX 20
#define HTTP_HEADERS_LENGTH_MAX 256
#define HTTP_BODY_LENGTH_MAX 8192
#define HTTP_STATUS_STRING_LENGTH_MAX 128

typedef struct {
  int version;
  int method;
  char path[HTTP_PATH_MAX];

  struct {
    char name[HTTP_HEADERS_LENGTH_MAX];
    char key[HTTP_HEADERS_LENGTH_MAX];
  } headers[HTTP_HEADERS_MAX];
  size_t header_count;

  char* body;
} http_request_t;

typedef struct {
  int version;
  int status;
  char status_string[HTTP_STATUS_STRING_LENGTH_MAX];

  struct {
    char name[HTTP_HEADERS_LENGTH_MAX];
    char key[HTTP_HEADERS_LENGTH_MAX];
  } response_headers[HTTP_HEADERS_MAX];
  size_t response_header_count;

  struct {
    char name[HTTP_HEADERS_LENGTH_MAX];
    char key[HTTP_HEADERS_LENGTH_MAX];
  } representation_headers[HTTP_HEADERS_MAX];
  size_t representation_header_count;

  char* body;
} http_response_t;

#endif
