// SPDX-License-Identifier: MIT

#ifndef _LOGLEVELS
#define _LOGLEVELS

#define LOGL_EMERG 0
#define LOGL_ALERT 1
#define LOGL_CRIT 2
#define LOGL_ERROR 3
#define LOGL_WARN 4
#define LOGL_NOTICE 5
#define LOGL_INFO 6
#define LOGL_DEBUG 7

#define LOGL_STRING_EMERG "EMERG"
#define LOGL_STRING_ALERT "ALERT"
#define LOGL_STRING_CRIT "CRIT"
#define LOGL_STRING_ERROR "ERROR"
#define LOGL_STRING_WARN "WARN"
#define LOGL_STRING_NOTICE "NOTICE"
#define LOGL_STRING_INFO "INFO"
#define LOGL_STRING_DEBUG "DEBUG"

#endif
